### ISSUE TITLE
Set up CI with GitHub Actions

### ISSUE THREAD

**Issue by jeff-cohere** [RDycore/RDycore#1]
We need

* a Docker container with PETSc installed
* a GitHub Actions workflow that builds RDycore against PETSc
* another GitHub Actions workflow that checks our code formatting with `clang-format`

**Comment by bishtgautam** [comment]
Add a Build status batch in the README e.g.

```
[![Build Status](https://github.com/TDycores-Project/TDycore/workflows/auto_pr_test/badge.svg)](https://github.com/TDycores-Project/TDycore/actions)
```
