### ISSUE TITLE
Update Docker image with Matt's vertical geometry fixes

### ISSUE THREAD

**Issue by jeff-cohere** [RDycore/RDycore#11]
When we start to deal with problems that involve differing elevations, we'll need some new PETSc code from the `knepley/fix-plex-geom-1d` branch. At the time of writing, we have plenty of work to do in planar (flat) geometry, so this isn't urgent, but it's worth tracking,.

**Comment by jedbrown** [comment]
The [branch merged](https://gitlab.com/petsc/petsc/-/merge_requests/5993) so this'll just be using current `main`.

**Comment by jeff-cohere** [comment]
Hmm, looks like it's in the `release` branch, and not current `main`. Does that make sense? I'll have to redo my PR.

**Comment by jedbrown** [comment]
Oh, 'twas a "bug fix" so targeted release, but there are other things in 'main' that I think RDycore will want very soon so I'll get it merged up there.

**Comment by jedbrown** [comment]
You should be good to go with `main` now.

**Comment by jeff-cohere** [comment]
Thanks! I have to step out, but I'll get this in first thing tomorrow.
