### ISSUE TITLE
Add a new Docker image that uses 64-bit PETSc integer indices

### ISSUE THREAD

**Issue by jeff-cohere** [RDycore/RDycore#116]
We've recently started using 64-bit integer indices now that we're running on large meshes. @jedbrown has an [open PETSc merge request](https://gitlab.com/petsc/petsc/-/merge_requests/7076) to make libCEED play nicely under these circumstances. When that merge request goes into PETSc's main branch, we should create new Docker images for PETSc built with both 32- and 64-bit integer indices to allow us to build and test under both configurations.

**Comment by jedbrown** [comment]
That MR merged.
