### ISSUE TITLE
Internal edges corresponding to ghost cells are getting added in the boundary data structure

### ISSUE THREAD

**Issue by bishtgautam** [RDycore/RDycore#122]
Shown below is an example of grid decomposition on 2 MPI ranks for a problem that can be run as follows:

```
cd driver/tests/swe_roe
/opt/local/bin/mpiexec-openmpi-mp -n 2 ../../rdycore_mms mms_dx1.yaml
```

![fullmesh](https://github.com/RDycore/RDycore/assets/8105979/38ee16f3-0b26-45fa-8b39-b2bc07baaa9d)
![rank0](https://github.com/RDycore/RDycore/assets/8105979/c56239f4-a09b-4748-8963-8de757d89f3b)
![rank1](https://github.com/RDycore/RDycore/assets/8105979/68e5df85-4eca-4833-8c28-1718e01d54c0)

If a boundary condition is not specified on an edge, RDycore automatically adds a reflective boundary condition during model setup in [InitBoundaries()](https://github.com/RDycore/RDycore/blob/main/src/rdysetup.c#L440C23-L440C37). When running in parallel, there are edges of the red ghost cells that are identified as "boundary" cells ([`num_unassigned_edges`](https://github.com/RDycore/RDycore/blob/main/src/rdysetup.c#L510)). Since these are ghost cells, RDycore shouldn't be considering them as unassigned edges.

Currently, the `InitBoundaries()` is called before `RDyMeshCreateFromDM()`. Thus, we don't know if the cells corresponding to `num_unassigned_edges` are internal or ghost cells when `InitBoundaries()` is called.

A possible fix could be that as a last step of setup, we revisit the boundaries and check if the last boundary condition is of a reflecting type and remove all edges from the last boundary condition that correspond to ghost cells. If after removing all edges corresponding to ghost cells, there are no edges in that boundary, we should reduce `num_boundaries` by one.

**Comment by jeff-cohere** [comment]
I wonder if we couldn't call `InitBoundaries` and its ilk after we perform the mesh decomposition. The sources/initial condtions have to be set up before the solvers, but I'm not sure we need the boundary information for that.
