### ISSUE TITLE
The natural vector is not distributed

### ISSUE THREAD

**Issue by bishtgautam** [RDycore/RDycore#125]
@knepley, While the natural vector is of the correct size, it is entirely on rank-0 and not distributed. I added [screenoutput of the global vector and natural vector](https://gist.githubusercontent.com/bishtgautam/c116e212e9d4555af8d3ce98a4037849/raw/87b52f74c5b2f5c73f429b5a76dd9b944f0dfc70/gistfile1.txt). The output is available [here](https://gist.githubusercontent.com/bishtgautam/c116e212e9d4555af8d3ce98a4037849/raw/87b52f74c5b2f5c73f429b5a76dd9b944f0dfc70/gistfile1.txt). You can reproduce the issue via:

```
git checkout bishtgautam/dm-bug
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=$PWD -DCMAKE_BUILD_TYPE=Debug
make -j4
cd driver/tests/swe_roe
/opt/local/bin/mpiexec-openmpi-mp -n 2 ../../rdycore ex2b_ic_file.yaml
```

**Comment by knepley** [comment]
Yes, it has the same distribution as the original mesh that we are mapping back to. I don't use natural vectors in the example, just ISes. I am having a hard time understanding why we want to do this. Maybe you could lay out the whole workflow so that the code will make more sense.

**Comment by bishtgautam** [comment]
I want to output data in the .h5 independent of how the mesh was distributed. The current natural vector is in the correct order, just that this approach isn't scalable because that natural vector is entirely on rank-0. I guess the IS being created for a natural vector is putting the entire data on rank 0.

**Comment by knepley** [comment]
"I want to output data in the .h5 independent of how the mesh was distributed." This is not precise enough. The mesh is already output independent of the distribution. You want something more since you are saving extra information. What exactly do you want to do, and how is it supposed to be executed?

**Comment by bishtgautam** [comment]
The mesh is 
```
ncdump -h DamBreak_grid5x10.exo
netcdf DamBreak_grid5x10 {
dimensions:
	num_dim = 3 ;
	num_nodes = 63 ;
	num_elem = 44 ;
	num_el_blk = 1 ;
	num_el_in_blk1 = 44 ;
	num_nod_per_el1 = 4 ;
	time_step = UNLIMITED ; // (0 currently)
	num_elem_var = 11 ;
variables:
	int eb_prop1(num_el_blk) ;
		eb_prop1:name = "ID" ;
	double coordx(num_nodes) ;
	double coordy(num_nodes) ;
	double coordz(num_nodes) ;
	int connect1(num_el_in_blk1, num_nod_per_el1) ;
		connect1:elem_type = "QUAD" ;

// global attributes:
		:api_version = 4.93 ;
		:version = 4.93 ;
		:floating_point_word_size = 8. ;
		:file_size = 1. ;
```

RDycore output data 
```
h5dump -H output/ex2b_ic_file-0.h5
HDF5 "output/ex2b_ic_file-0.h5" {
GROUP "/" {
   ATTRIBUTE "dmplex_storage_version" {
      DATATYPE  H5T_STRING {
         STRSIZE 6;
         STRPAD H5T_STR_NULLTERM;
         CSET H5T_CSET_ASCII;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SCALAR
   }
   ATTRIBUTE "petsc_version_git" {
      DATATYPE  H5T_STRING {
         STRSIZE 25;
         STRPAD H5T_STR_NULLTERM;
         CSET H5T_CSET_ASCII;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SCALAR
   }
   GROUP "0 0.000000E+00 hr" {
      DATASET "Height" {
         DATATYPE  H5T_IEEE_F64LE
         DATASPACE  SIMPLE { ( 44 ) / ( 44 ) }
      }
      DATASET "MomentumX" {
         DATATYPE  H5T_IEEE_F64LE
         DATASPACE  SIMPLE { ( 44 ) / ( 44 ) }
      }
      DATASET "MomentumY" {
         DATATYPE  H5T_IEEE_F64LE
         DATASPACE  SIMPLE { ( 44 ) / ( 44 ) }
      }
   }
   GROUP "geometry" {
      DATASET "vertices" {
         DATATYPE  H5T_IEEE_F64LE
         DATASPACE  SIMPLE { ( 63, 3 ) / ( 63, 3 ) }
      }
   }
   GROUP "viz" {
      GROUP "topology" {
         DATASET "cells" {
            DATATYPE  H5T_STD_I32LE
            DATASPACE  SIMPLE { ( 44, 4 ) / ( 44, 4 ) }
            ATTRIBUTE "cell_corners" {
               DATATYPE  H5T_STD_I32LE
               DATASPACE  SCALAR
            }
            ATTRIBUTE "cell_dim" {
               DATATYPE  H5T_STD_I32LE
               DATASPACE  SCALAR
            }
         }
      }
   }
}
}
```

The data in h5 in `/0 0.000000E+00 hr/Height` should be in the same order as data in `connect1`.

**Comment by knepley** [comment]
In the example I sent, the IS is partitioned like the distributed mesh, not like the original serial mesh. Isn't this what you want?

**Comment by bishtgautam** [comment]
This isn't a bug in the code but an issue with the mesh format. The HDF5 mesh must be in `-dm_plex_view_hdf5_storage_version 3.0.0`, as it is the only mesh format in which the mesh is read in parallel. If the mesh is read serially, the Natural vector is serial.
