### ISSUE TITLE
Add support for running ensemble calculations

### ISSUE THREAD

**Issue by jeff-cohere** [RDycore/RDycore#128]
Design points:

* We've decided to split the global MPI communicator into sub-communicators assigned to ensemble members within RDycore, allowing us to perform our own analysis
* We are adding an `ensemble` section to the YAML input file, [described here](https://github.com/RDycore/RDycore/blob/jeff-cohere/ensembles/docs/user/input.md#ensemble).
* We will allocate one GPU (device) to each ensemble member instead of sharing them between different ensemble members. The minimum ensemble size that uses an entire compute node is then determined by the number of available devices on that node, and larger ensembles should have a number of members that is a multiple of this minimum size.

Interested folks can follow the latest progress on this issue [in this branch](https://github.com/RDycore/RDycore/tree/jeff-cohere/ensembles).

**Comment by knepley** [comment]
The disadvantage of 2) is that we cannot do our own processing of the results, and instead reply on something outside RDyCore.

**Comment by jeff-cohere** [comment]
> The disadvantage of 2) is that we cannot do our own processing of the results, and instead reply on something outside RDyCore.

I don't think I understand this. Given that we have `PETSC_COMM_WORLD` and the communicator for each ensemble, why couldn't we do our own processing?

**Comment by knepley** [comment]
Oh, I meant if you were using a system that ran RDyCore from outside. If we split the comm ourselves and handle it, then yes it is the same.
