### ISSUE TITLE
Mesh generation and workflows: regions and surfaces for initial and boundary conditions, sources

### ISSUE THREAD

**Issue by jeff-cohere** [RDycore/RDycore#13]
After #12 is complete, we can add an input option that allows us to specify a set of inactive cells to be removed from the interior of the computational domain, effectively creating reflecting wall boundary conditions on the relevant edges. This allows us to compute a solution closer to the [2D dam-break problem](https://rdycore.atlassian.net/wiki/spaces/PD/pages/15237121/Flow+Partial+2D+dam+break+problem).

**Comment by jedbrown** [comment]
Is this for structured mesh? We don't need to deactivate cells if it's unstructured.

**Comment by jeff-cohere** [comment]
Unstructured, I believe. We were just discussing this as a possible "accelerator" that would let us avoid having to regenerate meshes when we wanted to change "internal" geometry. But if it's easy to "punch out" cells directly using DMPlex, I'm all for it.

**Comment by jedbrown** [comment]
If you label (`DMLabel`) cells you want to keep, then `DMPlexFilter()` will drop the rest. This works in parallel and you can redistribute afterward or not (no need if you're only filtering out a small fraction).

**Comment by jeff-cohere** [comment]
Excellent. We'll definitely use this. Then this task just becomes a matter of expressing the internal boundaries as part of the input.

**Comment by jedbrown** [comment]
Are you okay with creating a geometry in Gmsh, for example?

**Comment by jeff-cohere** [comment]
Sure, that works for me. I think we are probably going to use Darren's tool for generating some meshes, too. @bishtgautam , do you have thoughts on mesh generation?

**Comment by bishtgautam** [comment]
We will eventually create meshes using Darren's [JIGSAW tool](https://github.com/dengwirda/jigsaw). For now, we will write our own code to create idealized meshes in `.exo`.

**Comment by jedbrown** [comment]
What formats can Darren's tool write? I work most frequently with Gmsh and CGNS formats, but PETSc supports a bunch. It should be just a few minutes to set up the dam break geometry in Gmsh. Let me know if you'd like my help with that.

**Comment by jeff-cohere** [comment]
Thanks, @jedbrown . I think gmsh would be fine for this example. I've used it before, but it's always nice to know people who deal with Geometry. :-)

**Comment by jedbrown** [comment]
Here's a sample. Let me know if there's a repo you'd like me to drop this in. The boundaries are labeled and will become `Face Sets`.
![image](https://user-images.githubusercontent.com/3303/214436845-c78912e1-39f4-446e-bc6e-73f9d3dd1f63.png)
<details>

```gmsh
Lx = 100;
dx = 5;
Ly = 100;
y1 = 70;
y2 = -5;

// p1----l1-----p2  p3-----l5-----p4
// |            |   |             |
// |            l2  l4            |
// |            |   |             |
// |            p5--p6            |
// |                              |
// |                              |
// l12                            l6
// |            p7--p8            |
// |            |   |             |
// |            |   |             |
// |            l10 l8            |
// |            |   |             |
// |            |   |             |
// p9----l11----p10 p11-----l7----p12

Point(1) = {-Lx, Ly, 0};
Point(2) = {-dx, Ly, 0};
Point(3) = {dx, Ly, 0};
Point(4) = {Lx, Ly, 0};
Point(5) = {-dx, y1, 0};
Point(6) = {dx, y1, 0};
Point(7) = {-dx, y2, 0};
Point(8) = {dx, y2, 0};
Point(9) = {-Lx, -Ly, 0};
Point(10) = {-dx, -Ly, 0};
Point(11) = {dx, -Ly, 0};
Point(12) = {Lx, -Ly, 0};

Line(1) = {1, 2};
Line(2) = {2, 5};
Line(3) = {5, 6};
Line(4) = {6, 3};
Line(5) = {3, 4};
Line(6) = {4, 12};
Line(7) = {12, 11};
Line(8) = {11, 8};
Line(9) = {8, 7};
Line(10) = {7, 10};
Line(11) = {10, 9};
Line(12) = {9, 1};

Curve Loop(1) = {1:12};
Plane Surface(1) = {1};

Physical Curve("exterior", 1) = {1, 5, 6, 7, 11, 12};
Physical Curve("short_wall", 2) = {2:4};
Physical Curve("long_wall", 3) = {8:10};
Physical Surface(10) = {1};
```

</details>

**Comment by jeff-cohere** [comment]
This is perfect for now! Thanks, Jed.

**Comment by dengwirda** [comment]
Hi all,
For now we can export from jigsaw in *.vtk text (a'la Paraview). Can PETSc read this in?
Longer term we may want to consider what the best hierarchy is --- whether to go straight from jigsaw => PETSc, or also loop E3SM data formats in there too.
No worries to use gmsh for this kind of thing, though it's also possible to python script these kind of geometries [for jigsaw too](https://github.com/dengwirda/jigsaw-python/blob/d9d70e60fae9b5686c85113d1d1d4b21ae341789/tests/case_0_.py#L25).

**Comment by jedbrown** [comment]
PETSc supports VTK output, but not VTK input since it isn't a format intended for inputs (insufficient specification of boundary conditions and subdomains). We could use `meshio` to convert to a suitable input format or we can write a direct reader, but I don't think this is a good long-term workflow.

**Comment by bishtgautam** [comment]
I think should be exporting meshes from JIGSAW in: 
 - `.exo`, and 
 - DMPlex-supported `.h5` (see [Hapla et al. 2020](https://arxiv.org/abs/2004.08729)). 
 
 My guess is that I/O will be more scalable for meshes that are in `.h5` than `.exo`.
@jedbrown , @knepley , Thoughts?

**Comment by knepley** [comment]
It will be more scalable, but I think the main reason to consider this is (as Jed pointed out) that these formats allow us to store everything (BCs for example).

**Comment by dengwirda** [comment]
Okay, just to start, this seems to work as expected (as far as paraview is concerned at least):
```
    import meshio
    # jmsh is a jigsaw_msh_t object
    mesh = meshio.Mesh(
        points=jmsh.point["coord"],
        cells=[
            ("line", jmsh.edge2["index"]),  # edges on bnds
            ("triangle", jmsh.tria3["index"]),
        ]
    )
    mesh.write("test.xdmf")
```
Let me know if other data needs to be passed through.

**Comment by jedbrown** [comment]
Can you label boundaries?

**Comment by dengwirda** [comment]
Yep, as IDs-per-cell:
![dam-break-id-small](https://user-images.githubusercontent.com/10022384/216063844-97b941a3-2fe6-4f8a-ae60-14863781fb24.png)
Is there an `xdmf` format used for the labelling? It looks like I can pass a cell `ID` array through `meshio` for example.

**Comment by jedbrown** [comment]
I'm not a fan of Xdmf (especially as an input format) because it doesn't have a good way to specify boundary conditions. I think Gmsh is better supported by meshio and has good support for labeling boundaries (so you can pass the data in via API as you're doing, creating the surface elements and using `cell_sets` to label them).

**Comment by dengwirda** [comment]
Okay, is `xdmf `not the `*.h5` format for DMPlex discussed above? Maybe I misunderstood @bishtgautam and @knepley above?

**Comment by jedbrown** [comment]
Sort of. Xdmf is an XML header that can access arrays living in an HDF5 file. The XML makes it so tools like Paraview can interpret it. But the Xdmf working group is pretty defunct and it seems like an abandoned effort. The `.h5` format that Vaclav and Matt use has some parts that are not representable as Xdmf and I don't think you'll get meshio to write something that their parallel reader can use directly. I'd suggest letting meshio export as Gmsh format -- that'll take us a long way and we can revisit when we're running huge meshes.

**Comment by jeff-cohere** [comment]
I've renamed this issue to reflect its content. At this time, I believe we can get by without any "inline" mesh generation. Thanks for your help with Gmsh, @jedbrown .

**Comment by jeff-cohere** [comment]
I think we've addressed all the issues that we were discussing here. Our mesh generation workflow is evolving, so I'll close this and we can open a new mesh-workflow-related issue if we need to.
