### ISSUE TITLE
Flesh out the User Guide

### ISSUE THREAD

**Issue by jeff-cohere** [RDycore/RDycore#144]
At this point, we have a decent amount of infrastructure in place, so it's time to start thinking about documenting how to run things in RDycore. So far, we have a pretty good description of the configuration file format. Here are some things we need to add:

* Part 1: Running Standalone Calculations
    * The C and Fortran driver programs and their capabilities/purposes
    * Configuring output and checkpoints
    * Debugging (including `-pause` feature)
    * Running ensembles
* Part 2: Coupling with E3SM
    * TBD

**Comment by bishtgautam** [comment]
We have the first version of the User Guide is in place.
