### ISSUE TITLE
Segfault when running ensembles on Frontier and on Apple Silicon

### ISSUE THREAD

**Issue by jeff-cohere** [RDycore/RDycore#154]
@bishtgautam and I are encountering somewhat mysterious [segmentation faults](https://gist.github.com/jeff-cohere/82f4d0671710d13c41bf392f88eca727) when running ensemble simulations with RDycore on our Mac Mx laptops. Gautam sees a similar [segmentation fault on Frontier](https://gist.githubusercontent.com/bishtgautam/88f1fc9bd808ab453eff3f89def8e78f/raw/72e41acdd1ae7a4b76f768ab0de1b48d6f9f4241/gistfile1.txt) when running ensembles there. On our Linux laptops and workstations, no such errors occur, and Valgrind gives us a clean bill of health.

The errors seem to occur at different locations, indicating to me that something is wrong that isn't causing trouble on off-the-shelf Linux.

**Comment by knepley** [comment]
Can you get SEGV if you run under the debugger on the laptop? THen we would have a stack. Also, you should run it under Address Sanitizer using CLang.

**Comment by jeff-cohere** [comment]
Thanks for the suggestions, Matt. Gautam's building a debuggable PETSc on Frontier so we can better understand that issue. My laptop's not in front of me at the moment (before Gautam reported the Frontier issue, I thought this was just an Apple Silicon thing), but I can certainly try the debugger and AddressSanitizer this evening if we don't have a bead on it by then.

**Comment by jeff-cohere** [comment]
We have a fix for the memory error, but now it looks like an ensemble calculation is hanging on Perlmutter during the process of parsing YAML. I don't know how much exotic stuff is happening under the hood with the YAML parser, but it's just taking forever for some reason.
