### ISSUE TITLE
No output written out by MMS driver when num_refinements > 0

### ISSUE THREAD

**Issue by bishtgautam** [RDycore/RDycore#182]
No output is generated when running the following even though the `output` block is present in the `.yaml` file

```
cd <build-dir>/driver/tests/swe_roe
../../rdycore_mms mms_dx1.yaml
```

However, if `num_refinements: 3` is changed to `num_refinements: 0`, the MMS driver writes output

```
ls -l output
total 256
-rw-r--r--  1 bish218  staff  59960 May 31 15:25 mms_dx1-0.h5
-rw-r--r--  1 bish218  staff   1722 May 31 15:25 mms_dx1-000.xmf
-rw-r--r--  1 bish218  staff  59960 May 31 15:25 mms_dx1-500.h5
-rw-r--r--  1 bish218  staff   1744 May 31 15:25 mms_dx1-500.xmf
```

**Comment by bishtgautam** [comment]
For `mms_dx1.yaml`, the output filenames for refinements could be `mms_dx1-refinement<n>-0.h5`.

**Comment by jeff-cohere** [comment]
The code path for MMS convergence studies is sufficiently different that this would be tricky, and it turns out we can get outut for any specific refinement level by running single calculations using either the standalone RDycore driver or the MMS driver with the `-dm_refine` flag.
