### ISSUE TITLE
Add an option to enable/disable NetCDF and related features

### ISSUE THREAD

**Issue by jeff-cohere** [RDycore/RDycore#21]
In a perfect world, NetCDF would not be a colossal pain to properly configure and install on one's platform of choice. We do not live in that world, however.

We can sidestep this particular issue by adding a CMake option (`ENABLE_NETCDF`, say), that can be switched on or off depending on the level of agony visited upon a particular developer/user. We have input and output options that don't require it, and I think it's reasonable for someone to choose how they want to spend their time.

This is not urgent--just sticking this here to remind myself to include this option when our input/output file support gets a little more mature.

**Comment by jedbrown** [comment]
Does rdycore use netcdf directly? Is this about deciding which tests to skip when netcdf/exodus are not configured into PETSc? If so, we could make that determination at run-time.

**Comment by jeff-cohere** [comment]
Yeah, I was thinking that, too. We don't use it directly and I can't really think of a reason for us to start. So maybe this is a non-issue.

**Comment by jeff-cohere** [comment]
Let's leave NetCDF (and file I/O in general) to PETSc and see how far we can get.
