### ISSUE TITLE
Allow output to be written out at a specified temporal frequency

### ISSUE THREAD

**Issue by bishtgautam** [RDycore/RDycore#211]
Currently, output can be written out at a specified number of model steps. e.g. `interval: 100`
tells the model to write output every 100 model steps. This is okay for the case when the model
takes a constant time step. However, with time step adaptivity (https://github.com/RDycore/RDycore/pull/210),
we need the ability to specify output to be written at fixed time intervals (say 30 mins).

**Comment by jedbrown** [comment]
If we were to implement this upstream in PETSc, what would be a good name for the time interval instead of step interval?
