### ISSUE TITLE
Update PETSc docker to v3.22.0

### ISSUE THREAD

**Issue by bishtgautam** [RDycore/RDycore#221]
We need @markadams's fix to `VecCopy` for GPUs, which is included in PETSc v3.22.0.

@jeff-cohere I have a branch where I'm updating the PETSc installation setting for Perlmutter and Frontier. I will open a PR when the branch is ready and then you can add a new commit in it that updates the PETSc Docker image.

**Comment by jeff-cohere** [comment]
Thanks, @bishtgautam . I'll take care of this and the crash issue early next week!

**Comment by bishtgautam** [comment]
I opened #222 for you to add a new commit updating the docker image. Thanks.
