### ISSUE TITLE
Add support for specifying an IC for the whole domain

### ISSUE THREAD

**Issue by bishtgautam** [RDycore/RDycore#23]
Presently, IC is specified for each region in the `.yaml` as:

```
initial_conditions:
  1: # upstream region
    flow: dam_top_ic
  2: # downstream region
    flow: dam_bottom_ic

# NOTE: We use reflecting boundary conditions for the boundary, top_wall, and
# NOTE: bottom_wall surfaces

flow_conditions:
  dam_top_ic:
    type: dirichlet
    height: 10
    momentum: [0, 0]
  dam_bottom_ic:
    type: dirichlet
    height: 5
    momentum: [0, 0]
```

Add the ability to specify an IC for the entire domain without the need to define regions via

```
initial_condition
  file: <petsc-binary-vector-in-natural-order.bin>
```

**Comment by jeff-cohere** [comment]
@bishtgautam has suggested that we add domain boundary faces for a mesh that doesn't have such a face set already. Internal boundaries, however, still have to be specified by face sets. I think this is really easy, because PETSc actually provides a way to mark domain boundary faces.

**Comment by knepley** [comment]
Right now you can mark the entire boundary with `DMPlexMarkBoundaryFaces()`. We could also add something to mark the different normal directions, but if you have a box I would be inclined to use the built-in box creation which marks the faces automatically.

**Comment by jeff-cohere** [comment]
Yup, that's the approach.
