### ISSUE TITLE
Add XDMF output capability

### ISSUE THREAD

**Issue by jeff-cohere** [RDycore/RDycore#27]
Now that we've got a simulator that can run alongside our toy problem demos, it's a good time to add some features for inspecting output.

**Comment by jedbrown** [comment]
This exists in the hdf5_xdmf viewer format. The petsc_gen_xdmf.py script creates the XML index file. (I'll acknowledge not being a fan of Xdmf, but if that's the format you want, that's how it currently works.)

**Comment by jeff-cohere** [comment]
Thanks, @jedbrown! I think this is the output format preferred by @bishtgautam for now. I know it has several shortcomings, but it seems to have traction in this community.

**Comment by bishtgautam** [comment]
@knepley summarized my thinking on the topic. Add XDMF support to be able to visualize the HDF5 output.

**Comment by jedbrown** [comment]
Right, I use HDF5 via CGNS because it's more expressive and I don't need to fiddle with XML.

**Comment by knepley** [comment]
Does ParaView support CGNS?

**Comment by jedbrown** [comment]
Yes, I use it every day.

**Comment by jeff-cohere** [comment]
We can always add support for CGNS if we find XDMF too grating. The fact that PETSc supports both formats makes it fairly cheap for us to do so, right?

Now I have a question regarding the XDMF implementation, and more broadly the relationship between output files and file-based reading of initial conditions.

@bishtgautam , you have suggested we adopt [PFlotran's approach to writing XDMF files](https://bitbucket.org/pflotran/pflotran/src/b3026258920a8645419a33f4d0f733972365c7b7/src/pflotran/output_hdf5.F90#lines-404), which separates the solution vector into components to be written to HDF5 files. You've also mentioned that we should allow such HDF5 files to be read in with our file-based initial conditions. Should we lay out some explicit rules for files that we support as valid initial conditions files? Here's what I can figure out so far:

* We support reading binary files containing the entire solution vector written [this way, e.g. by ex2b](https://github.com/RDycore/toy-problems/blob/main/swe_roe/ex2b.c#L2029)
* We support reading HDF5 files written by RDycore itself to XDMF datasets, with the solution vector decomposed into separate single-component vectors
* Anything else?

**Comment by bishtgautam** [comment]
PFLOTRAN's XDMF format puts data within multiple `GROUPS` in `.h5` as:

```
h5dump -H output-1/mixed_implicit.h5 | grep GROUP
GROUP "/" {
   GROUP "   0 Time  0.00000E+00 d" {
   GROUP "   1 Time  4.00000E+01 d" {
   GROUP "Domain" {
```

In the RDycore we can support IC:
1.  In a PETSc binary (e.g., a PETSc Vec with 3 DOFs)
```
initial_conditions:
  file: DamBreak_grid5x10_wetdownstream.IC
  format: binary
```

2. From XDMF:
```
initial_conditions:
  file: DamBreak_grid5x10_wetdownstream.h5
  format: xdmf
  group_name: "   1 Time  4.00000E+01 d"
```

where in the `.h5` file the data would be something like:
```
- GROUP "   1 Time  4.00000E+01 d"
    - DATASET "Water_Height"
    - DATASET "X_Momentum"
    - DATASET "Y_Momentum"
```

**Comment by jedbrown** [comment]
Sorry about my slow response, @jeff-cohere. Here's a demo of the capability. This literal run (with `-dm_refine`) needed a patch on my branch (https://github.com/rdycore/rdycore/commit/fd7c8438c72ef370e5d82ab428fe1a3c91348334, which I see conflicts with something you did recently). Anyway, the important thing is `-ts_monitor_solution cgns:out.cgns` to write CGNS. The file will contain the whole time series, though it can be sliced into [batches](https://petsc.org/main/manualpages/Viewer/PETSCVIEWERCGNS/) with an arbitrary interval ([`-ts_monitor_solution_interval`](https://petsc.org/main/manual/ts/#monitoring-and-visualizing-solutions)).

https://gitlab.com/petsc/petsc/-/merge_requests/6396#note_1373485617

**Comment by jeff-cohere** [comment]
Thanks, @jedbrown!
