### ISSUE TITLE
Support multiple mesh topologies with XDMF output

### ISSUE THREAD

**Issue by jeff-cohere** [RDycore/RDycore#39]
XDMF output hasn't been tested on meshes having e.g. triangles and quads, and I'm not sure the data is mapped correctly in that case. We might have to use PFlotran's approach to storing mesh topology data instead of PETSc's for this.

**Comment by jeff-cohere** [comment]
This may actually work. Let's see if mixed triangle/quad meshes exhibit any problems before prioritizing work on this.

**Comment by jedbrown** [comment]
BTW, mixed topology is on my plate to support in CGNS. Might be a week or two, but soon. We also need it for CFD.

**Comment by jeff-cohere** [comment]
This issue has been addressed, and the outstanding issues with intermixed local/ghost cells in multiple topologies is being handled in PR #133, so I'm closing it.
