### ISSUE TITLE
First pass at a Developer Guide

### ISSUE THREAD

**Issue by jeff-cohere** [RDycore/RDycore#4]
The Developer Guide lives [here](https://github.com/RDycore/RDycore/tree/main/docs/developer). Topics of interest:

* Overview
    * RDycore is a dycore with a very small interface for interacting with a land "host" model, not a library for developing dycores
    * Standalone C and Fortran drivers
    * Integration with E3SM
        * Diagram showing interaction between ELM and RDycore
    * Development Tools
        * Standalone RDycore driver
        * MMR driver (convergence test)
* Development Process
    * Git workflow
    * Code style
    * CMake build system
    * Testing system
    * GitHub testing environment
* Code Structure and Organization
    * A Brief Tour (source files)
    * The RDycore Object and its Lifecycle (initialization, setup, running, analysis, finalization)
    * Computational Domain (regions and boundaries)
    * Operators (fluxes, source terms)
    * Input
    * Output (including time series)
    * Checkpoints and Restarts
    * Ensembles
        * Ensemble configuration process
        * Conditions that differ between ensemble mode and single-simulation mode
    * Fortran Support
* Standalone Programs
* ...?

**Comment by jeff-cohere** [comment]
We should describe our Fortran<->C bridge here, along with how to pass PETSc objects from Fortan to C using the Fortran 2003 ISO C bindings. Notes from today's session:

We have our working examples

>To pass a Vec to a C function:
```
PetscFortranAddr, value, intent(in) :: vec
```
> and to pass a Vec * to a C function (assuming you’re allocating it and don’t care about its current state):
```
PetscFortranAddr,   intent(out) :: vec
```

**Comment by bishtgautam** [comment]
- Add a section describing the setup of CEEDOperators being used for SWE
  - https://github.com/RDycore/RDycore/blob/main/src/swe/swe_ceed.c#L292
  - https://github.com/RDycore/RDycore/blob/main/src/swe/swe_ceed.c#L394
