### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by arcowie** [RDycore/RDycore#43]
Hello,
  I am trying to build RDycore on an linux system runnning Ubuntu 22.04.2 LTS.  
**output from make -j:**
Scanning dependencies of target rdycore_f90
[  2%] Creating directories for 'yaml_proj'
[  5%] Creating directories for 'cmocka_proj'
[  8%] Building Fortran object src/f90-mod/CMakeFiles/rdycore_f90.dir/rdycore.F90.o
[ 11%] No download step for 'yaml_proj'
[ 13%] No download step for 'cmocka_proj'
[ 16%] No update step for 'yaml_proj'
[ 19%] No update step for 'cmocka_proj'
[ 22%] No patch step for 'yaml_proj'
[ 25%] No patch step for 'cmocka_proj'
[ 27%] Performing configure step for 'yaml_proj'
[ 30%] Performing configure step for 'cmocka_proj'
[ 33%] Linking Fortran static library librdycore_f90.a
[ 33%] Built target rdycore_f90
-- yaml_proj configure command succeeded.  See also /home/arcowie/rdycore/build/external/libyaml/src/yaml_proj-stamp/yaml_proj-configure-*.log
[ 36%] Performing build step for 'yaml_proj'
-- yaml_proj build command succeeded.  See also /home/arcowie/rdycore/build/external/libyaml/src/yaml_proj-stamp/yaml_proj-build-*.log
[ 38%] Performing install step for 'yaml_proj'
-- yaml_proj install command succeeded.  See also /home/arcowie/rdycore/build/external/libyaml/src/yaml_proj-stamp/yaml_proj-install-*.log
[ 41%] Completed 'yaml_proj'
[ 41%] Built target yaml_proj
[ 44%] Building C object src/CMakeFiles/rdycore.dir/read_config_file.c.o
[ 47%] Building C object src/CMakeFiles/rdycore.dir/rdycore.c.o
[ 50%] Building C object src/CMakeFiles/rdycore.dir/physics_swe.c.o
[ 52%] Building C object src/CMakeFiles/rdycore.dir/print_config.c.o
[ 55%] Building C object src/CMakeFiles/rdycore.dir/rdymesh.c.o
[ 58%] Building C object src/CMakeFiles/rdycore.dir/rdyrun.c.o
[ 61%] Building C object src/CMakeFiles/rdycore.dir/rdysetup.c.o
[ 63%] Linking C static library librdycore.a
[ 63%] Built target rdycore
Scanning dependencies of target rdycore_f90_exe
[ 66%] Building C object driver/CMakeFiles/rdycore_exe.dir/main.c.o
[ 69%] Building Fortran object driver/CMakeFiles/rdycore_f90_exe.dir/main.F90.o
[ 72%] Linking C executable rdycore
[ 75%] Linking Fortran executable rdycore_f90
[ 75%] Built target rdycore_exe
/usr/bin/ld: ../src/librdycore.a(rdyrun.c.o): undefined reference to symbol 'MPI_Bcast'
/usr/bin/ld: /home/arcowie/petsc/arch-linux-rdycore-debug/lib/libmpi.so.12: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [driver/CMakeFiles/rdycore_f90_exe.dir/build.make:100: driver/rdycore_f90] Error 1
make[1]: *** [CMakeFiles/Makefile2:1228: driver/CMakeFiles/rdycore_f90_exe.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
-- cmocka_proj configure command succeeded.  See also /home/arcowie/rdycore/build/external/cmocka/src/cmocka_proj-stamp/cmocka_proj-configure-*.log
[ 77%] Performing build step for 'cmocka_proj'
-- cmocka_proj build command succeeded.  See also /home/arcowie/rdycore/build/external/cmocka/src/cmocka_proj-stamp/cmocka_proj-build-*.log
[ 80%] Performing install step for 'cmocka_proj'
-- cmocka_proj install command succeeded.  See also /home/arcowie/rdycore/build/external/cmocka/src/cmocka_proj-stamp/cmocka_proj-install-*.log
[ 83%] Completed 'cmocka_proj'
[ 83%] Built target cmocka_proj
make: *** [Makefile:146: all] Error 2

**cmake output:**
-- The C compiler identification is GNU 11.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- The Fortran compiler identification is GNU 11.3.0
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Check for working Fortran compiler: /usr/bin/gfortran - skipped
-- The CXX compiler identification is GNU 11.3.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- petsc_lib_dir /home/arcowie/petsc/arch-linux-rdycore-debug/lib
-- Recognized PETSc install with single library for all packages
-- Performing Test MULTIPASS_TEST_1_petsc_works_minimal
-- Performing Test MULTIPASS_TEST_1_petsc_works_minimal - Success
-- Minimal PETSc includes and libraries work.  This probably means we are building with shared libs.
-- Found PETSc: /home/arcowie/petsc/arch-linux-rdycore-debug/include;/home/arcowie/petsc/include (found version "3.19.1.99") 
-- Configuring RDycore (Debug)
-- Generating project files in build directory: /home/arcowie/rdycore/build
-- C compiler is /home/arcowie/petsc/arch-linux-rdycore-debug/bin/mpicc (GNU 11.3.0)
-- Fortran compiler is /usr/bin/gfortran (GNU 11.3.0)
-- Configuring RDycore v0.1.0
-- Installation prefix is /home/arcowie/rdycore/debug
-- Valgrind found. Enabling `make memcheck`
-- Configuring done
-- Generating done
-- Build files have been written to: /home/arcowie/rdycore/build

**PETSc build options used:**
--PETSC_ARCH=arch-linux-rdycore-debug --download-ctetgen --download-eigen --download-f2cblaslapack=1 --download-hdf5 --download-libceed --download-metis --download-mpich --download-parmetis --download-pragmatic --download-triangle --fc=1 --with-cxx-dialect=C++11 --with-fc=gfortran --with-hwloc=0  --with-clean

Output from nm -o $PETSC_DIR/$PETSC_ARCH/lib/libmpifort.so.12 | grep Bcast:
/home/arcowie/petsc/arch-linux-rdycore-debug/lib/libmpifort.so.12:                 U MPI_Bcast
/home/arcowie/petsc/arch-linux-rdycore-debug/lib/libmpifort.so.12:                 U MPI_Bcast_c
/home/arcowie/petsc/arch-linux-rdycore-debug/lib/libmpifort.so.12:                 U MPI_Bcast_init
/home/arcowie/petsc/arch-linux-rdycore-debug/lib/libmpifort.so.12:                 U MPI_Bcast_init_c
/home/arcowie/petsc/arch-linux-rdycore-debug/lib/libmpifort.so.12:00000000000aaf18 t MPIR_Bcast_cdesc
/home/arcowie/petsc/arch-linux-rdycore-debug/lib/libmpifort.so.12:00000000000ab001 t MPIR_Bcast_cdesc_large
/home/arcowie/petsc/arch-linux-rdycore-debug/lib/libmpifort.so.12:00000000000ab0ed t MPIR_Bcast_init_cdesc
/home/arcowie/petsc/arch-linux-rdycore-debug/lib/libmpifort.so.12:00000000000ab1f4 t MPIR_Bcast_init_cdesc_large

**Comment by bishtgautam** [comment]
@arcowie, @jeff-cohere recently fixed an error in CMake for my Mac that is using M1 chip. Are you using the latest master?

**Comment by jeff-cohere** [comment]
I agree with Gautam that this error would likely be fixed with the latest `main` branch.,

**Comment by arcowie** [comment]
Thank you.  I checked out main branch, pulled and it built.  I was in the jed/ceed-flux branch because of the project I was working on.
