### ISSUE TITLE
Use adaptive dt

### ISSUE THREAD

**Issue by bishtgautam** [RDycore/RDycore#44]
Instead of using fixed `dt`, figure out how to use TS to include dt adaptivity. Add examples in the repo that use different explicit time integration algos.

**Comment by jedbrown** [comment]
This can be done with https://petsc.org/main/manualpages/TS/TSSetCFLTimeLocal/.

I recommend `-ts_type ssp` as default explicit integrator for use with finite volume methods. It's significantly more efficient and accurate than forward Euler while still being strongly stable (positivity preserving if the spatial discretization is).

**Comment by bishtgautam** [comment]
`TSSetCFLTimeLocal` is definitely what I was looking at but it seems there isn't any PETSc example that is using it. Would it be possible for you to edit an existing PETSc example to demonstrate its usage?

**Comment by bishtgautam** [comment]
#210 fixed this issue.
