### ISSUE TITLE
XDMF output broken for parallel runs

### ISSUE THREAD

**Issue by bishtgautam** [RDycore/RDycore#45]
The VisIt cannot load the XDMF output written out for a parallel run.

```
cd build/driver/tests/swe_roe
/opt/local/bin/mpiexec-openmpi-mp -n 2 ../../rdycore ex2b.yaml
```

I noticed that the vertices in `/geometry/vertices` between a serial and parallel run differ.  The `/viz/topology/cells` are also different. We should be writing out `/geometry/vertices` and `/viz/topology/cells` that are the same for serial and parallel runs. We probably need to tell DMPlex to save natural vertex ids before distributing the DMPlex. Additionally, we may need to add 1 fake DOFs on vertices.

**Comment by jeff-cohere** [comment]
I can confirm that `/geometry/vertices` and `/viz/topology/cells` do indeed differ between serial and parallel runs.

**Comment by jeff-cohere** [comment]
@knepley , does data written by the XDMF viewer via `DMView` write out grid topology/geometry data in natural order if `DMSetUseNatural` has been called with `PETSC_TRUE`?

**Comment by knepley** [comment]
No, but we can probably add that. We have been focused on checkpointing, which is agnostic to the order.

**Comment by jeff-cohere** [comment]
If it's a reasonable thing to expect for `DMView` to respect `DMSetUseNatural`, that would be great!

**Comment by jeff-cohere** [comment]
@knepley , here's the issue we've been using to track the XDMF output behavior.

**Comment by knepley** [comment]
In the email thread, I suggested using `VecGetSize()` on the coordinate vector and dividing by the spatial dimension.

**Comment by jeff-cohere** [comment]
I'm closing this issue, since I believe it's been addressed properly now.
