### ISSUE TITLE
Implement the updated input spec to associate material properties with regions

### ISSUE THREAD

**Issue by jeff-cohere** [RDycore/RDycore#47]
We have proposed a new [input specification](https://rdycore.atlassian.net/wiki/spaces/PD/pages/24576001/RDycore+configuration+file) that adds a couple of sections to our YAML format, allowing us to assign specific material parameters to cells within specific regions.

This issue tracks the implementation of this new capability.

## Details

* We should remove the hard-coded `N_mannings` [here](https://github.com/RDycore/RDycore/blob/main/src/physics_swe.c#L603).

**Comment by jeff-cohere** [comment]
@bishtgautam , do you have a list of important material properties that you'd like to start with? We could just start with the Manning coefficient and add them as needed.

**Comment by bishtgautam** [comment]
We only need Manning's coefficient to begin with.
