### ISSUE TITLE
Add support to output data in multiple formats

### ISSUE THREAD

**Issue by bishtgautam** [RDycore/RDycore#49]
Currently, RDycore can only output data in only one of the three supported formats via:

```
output:
  format: xdmf
  frequency: 100
```

```
output:
  format: cgns
  frequency: 100
```

```
output:
  format: binary 
  frequency: 100
```

Need the capability to output data in multiple formats as some formats are easy to use for post-processing, while others are good for visualization.

**Comment by jedbrown** [comment]
Purely from a storage perspective (not soaking your quota or slowing down the app to write), I'd hope one format is ultimately enough. But I also get that something like this request should be supported. A quick thing in PETSc options is to have multiple calls to `VecViewFromOptions` under different string keys, so you'd have something like this
```yaml
ts_monitor:
  solution: cgns:sol.cgns
  diagnostics: hdf5:diag.h5:hdf5_xdmf
```

**Comment by jeff-cohere** [comment]
@bishtgautam , do you think we still need this capability?

**Comment by bishtgautam** [comment]
This isn't needed presently, so I'm closing this issue.
