### ISSUE TITLE
Diagnostic output: boundary fluxes

### ISSUE THREAD

**Issue by jeff-cohere** [RDycore/RDycore#63]
For the Houston Harvey flooding experiments, we would like to generate a tab-delimited time series file containing accumulated boundary fluxes for the components of the solution to the shallow water equations. The following columns would appear in such a file:

1. simulation time (in desired units)
2. (global) index of boundary edge
3. integer ID indicating the boundary to which the boundary edge belongs
4. integer ID indicating the type of boundary condition on the boundary edge
6. water mass flux
7. x-momentum flux
8. y-momentum flux
9. boundary edge normal x component
10. boundary edge normal y component

Boundary edges that are not explicitly assigned boundary conditions in the input YAML file do not appear in this file.

The file consists of rows containing the above information, with fluxes accumulated since the preceding row was printed. MPI rank 0 gathers all necessary information and appends a new row to the file at the desired dump interval as specified in the YAML file.

This means we'll need a parameter in the YAML file that defines the number of steps between boundary flux rows being appended to the file. We can do this by adding a subsection to the `output` section of the file--something like

```
output:
    ...
    time_series:
        boundary_fluxes: <number of steps between accumulated fluxes>
```

@bishtgautam

**Comment by jedbrown** [comment]
How many of these boundary edges do you need? Would it be possible to label them (e.g., with "Face Sets" or another label)? One of the reasons is that if you just use global edge numbers, you need extra code to interpret a grid refinement study. I'd rather talk about physical surfaces that can be one or more edge, and the simulation code sums over those edges to create the CSV output.

Also, if you don't know the edge orientation, you probably want to output the edge normal in this CSV output.

**Comment by jeff-cohere** [comment]
Good points, Jed. I think it would be easy to include the "boundary ID" with each boundary edge/flux, which should match the face set index read from the mesh file (and preserved by the refinement scheme). And the edge orientation would also be easy to add.

Do you two think we should use a CSV format instead of tab-delimited column data? I can see how that might interoperate better with tools, though it's very easy to go back and forth between the two.

**Comment by jedbrown** [comment]
Tab vs comma separated doesn't matter much -- either is equivalently easy to read by most software.
