### ISSUE TITLE
Add performance profiling capability

### ISSUE THREAD

**Issue by jeff-cohere** [RDycore/RDycore#7]
It would be helpful for us to have a systematic way to analyze performance. PETSc offers a built-in way of doing this, and E3SM has its own set of performance analysis libraries/tools.

**Comment by knepley** [comment]
One thing I am trying to add into PETSc is automated analysis. It is not perfect, but here is an example: https://petsc.org/main/tutorials/performance/guide_to_TAS/

**Comment by jeff-cohere** [comment]
Love it! Maybe we can help you bang it into shape.

**Comment by bishtgautam** [comment]
We are using `-log_view -log_view_gpu_time` to get performance profiling.
