### ISSUE TITLE
Issues with boundary flux output

### ISSUE THREAD

**Issue by bishtgautam** [RDycore/RDycore#71]
Currently, there are a few issues that I found with the `output/boundary_fluxes.dat`.

1. The file is currently appended instead of overwritten. When we add the capability in the model to restart a run, then the file can be appended, but for now, that file should be overwritten.

2. If coupling_interval is on, the model is incorrectly writing an entry in the file with values for h/hu/hv as 0.0. The error can be reproduced via:

```
cd build/driver/tests/swe_roe
```

Edit `ex2b.yaml` 
```
time:
  #final_time: 0.005
  #unit: hours
  #max_step: 1000
  final_time: 0.03
  time_step: 0.01
  coupling_interval: 0.01
  unit: seconds
```

Then run the model via:
```
../../rdycore_f90 ex2b.yaml -ts_monitor
DETAIL: ==========================================================
DETAIL: RDycore (input read from ex2b.yaml)
DETAIL: ==========================================================
DETAIL: Physics:
DETAIL:   Flow:
DETAIL:     Bed friction: disabled
DETAIL:   Sediment model: disabled
DETAIL:   Salinity model: disabled
DETAIL: Numerics:
DETAIL:   Spatial discretization: finite volume (FV)
DETAIL:   Temporal discretization: forward euler
DETAIL:   Riemann solver: roe
DETAIL: Time:
DETAIL:   Final time: 0.03 seconds
DETAIL: Logging:
DETAIL:   Primary log file: <stdout>
DETAIL: Restart:
DETAIL:   (disabled)
DETAIL: Advancing from t = 0. to 0.01...
0 TS dt 0.01 time 0.
DETAIL: Step 0: writing XDMF HDF5 output at t = 0. sec to output/ex2b-0.h5
DETAIL: Step 0: writing XDMF XMF output at t = 0. sec to output/ex2b-0.xmf
1 TS dt 0.01 time 0.01
DETAIL: Advancing from t = 0.01 to 0.02...
1 TS dt 0.01 time 0.01
2 TS dt 0.01 time 0.02
DETAIL: Advancing from t = 0.02 to 0.03...
2 TS dt 0.01 time 0.02
3 TS dt 0.01 time 0.03
```
The issue in the `output/boundary_fluxes.dat` is that there are two entries corresponding to time `1.000000e-02` and `2.000000e-02`.
```
>cat output/boundary_fluxes.dat | grep 11
0.000000e+00	11	2	2	0.000000e+00	0.000000e+00	0.000000e+00	1.000000e+00	-0.000000e+00
1.000000e-02	11	2	2	0.000000e+00	4.903000e+00	0.000000e+00	1.000000e+00	-0.000000e+00
1.000000e-02	11	2	2	0.000000e+00	0.000000e+00	0.000000e+00	1.000000e+00	-0.000000e+00
2.000000e-02	11	2	2	0.000000e+00	4.903000e+00	0.000000e+00	1.000000e+00	-0.000000e+00
2.000000e-02	11	2	2	0.000000e+00	0.000000e+00	0.000000e+00	1.000000e+00	-0.000000e+00
3.000000e-02	11	2	2	0.000000e+00	4.892554e+00	0.000000e+00	1.000000e+00	-0.000000e+00
```
Looking at the `-ts_monitor` output, it appears that for the second and third coupling time stepping, the `TS` is taking two steps instead of one. I'm not sure if the incorrect output in `output/boundary_fluxes.dat` is because `TS` is incorrectly taking two steps.

**Comment by jeff-cohere** [comment]
I think you're right that this is related to how often the TS monitors are being called, but it looks like `TSSolve` is only being called once per timestep. So we're getting monitor output (including boundary fluxes) at the beginning and the end of each coupling interval. I'll try to figure out how to eliminate the beginning-of-step monitoring output.

**Comment by jedbrown** [comment]
Normally you would call `TSSolve` once for many time steps. If you really want to just do one step without monitoring, you can call `TSStep`.

**Comment by jeff-cohere** [comment]
Yeah, this is a special case in which the time step encompasses the entire coupling interval, so I'm not too worried about it. PR #72 fixes the boundary flux output so it works in this case as well as the general case.
