### ISSUE TITLE
Implement boundary flux accumulation in libCEED implementation

### ISSUE THREAD

**Issue by jeff-cohere** [RDycore/RDycore#83]
Currently, we can compute boundary fluxes using our PETSc implementation of the Riemann solver, but we also need this in a GPU setting with libCEED because this is a significant mechanism for coupling with E3SM.

It's probably easiest for us to formulate the boundary fluxes in terms of their contributions to neighboring cells so we can make use of CEED's work arrays on the same space we're using for the solution.

UPDATE: @bishtgautam and I discussed this task earlier today. The summary of our discussion is:

* We can accumulate fluxes in a stride-9 vector (3 DoF x 3 faces) for each cell, and designate this vector as a passive input/output during the RDycore integration, and then we can do whatever we need to do with this info when we do coupling data transfer at the end of the coupling timestep (or whenever)
* While we could (in principle, at least) restrict the accumulation of fluxes to boundary cells, we are going to do the accumulation on all cells (including interior cells) in case we want to plot velocity/flow vectors.

**Comment by bishtgautam** [comment]
After our discussion, I realized that we should generalize the stride of the vector to be 3 DOFs x Max_faces_of_a_cell to support meshes comprising of triangles, quads, or both cell types.

**Comment by jedbrown** [comment]
This sounds like a pretty heavy vector and I'm not clear on why it's needed, versus either ghost cells or a face operator that populates the external (ghost) cell state and solves its Riemann problem.

**Comment by bishtgautam** [comment]
We **_need_** to accumulate fluxes going through boundary faces over multiple time steps. So, the approach that we came up with is to save the fluxes through edges in a cell-strided vector. In the current approach, we will be storing a duplicate copy of each flux. While we are adding this infrastructure for boundary fluxes, I thought we should also save the internal fluxes.

**Comment by jeff-cohere** [comment]
@jedbrown , I didn't realize that we could define a "face" (edge) operator. That would probably be a better way to attack this feature, since it expresses the right relationship between edges and adjoining cells. Do you have any examples of face operators in existing codes?

**Comment by jedbrown** [comment]
The current Riemann flux operator is on edges. Any such operator can store the result on the edges or accumulate it into adjacent cells.

**Comment by jeff-cohere** [comment]
So it is! If there's a way to store the resulting fluxes on edges and subsequently use these fluxes to compute the adjacent cell values (via another operator, perhaps), I think we have what we need.

**Comment by jedbrown** [comment]
Of course, you just need an array to store the single output, and a trivial restriction (can be strided).

**Comment by jeff-cohere** [comment]
Yep, I think I've got something cooking...

**Comment by jeff-cohere** [comment]
The remaining work on this task is to provide a function that copies boundary flux data into a given array and resets the boundary fluxes to zero. This can be done after we determine how E3SM couples with RDycore.

**Comment by bishtgautam** [comment]
For the record, we need an equivalent of the [`RDyCeedUpdateSourceTerm()` ](https://github.com/RDycore/RDycore/blob/main/src/swe/physics_swe.c#L109-L135) for BC.

**Comment by jeff-cohere** [comment]
> For the record, we need an equivalent of the [`RDyCeedUpdateSourceTerm()` ](https://github.com/RDycore/RDycore/blob/main/src/swe/physics_swe.c#L109-L135) for BC.

For updating time-dependent boundary conditions, correct?

**Comment by bishtgautam** [comment]
I see your point that I lumped two developments into one. The work can be done in stages:
1. Implement support for time-invariant dirichlet BC in CEED (i.e. extend [swe_ceed_operators.c#L136-L147](https://github.com/RDycore/RDycore/blob/main/src/swe/swe_ceed_operators.c#L136-L147)), then
2. Implement the support for time-dependent dirichlet BC in CEED (similar to [RDyCeedUpdateSourceTerm() ](https://github.com/RDycore/RDycore/blob/main/src/swe/physics_swe.c#L109-L135)).

**Comment by jeff-cohere** [comment]
Actually, I think it's fine to do both of these at once, since there aren't a lot of us working on this code at the moment. I was just making sure I understood your comment.
