### ISSUE TITLE
Create a test program that uses RDycore the way E3SM would

### ISSUE THREAD

**Issue by jeff-cohere** [RDycore/RDycore#85]
This allows us to try out ideas for coupling RDycore to E3SM while preserving the simple structure of our driver programs.

NOTE: When this is completed, we can remove the call to `RDySetLogFile` from our F90 driver program.

**Comment by bishtgautam** [comment]
The current RDycore driver is [mosart/src/rdycore/rdycoreMod.F90](https://github.com/RDycore/E3SM/blob/bishtgautam/mosart-rdycore/78a5ea1613-2023-08-07/components/mosart/src/rdycore/rdycoreMod.F90)

**Comment by jeff-cohere** [comment]
Is there a corresponding YAML input file for `rdycoreMod.F90` that you've used for testing?

**Comment by bishtgautam** [comment]
For testing, I have been using`driver/tests/swe_roe/ex2b.yaml`.
